// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { BylineSummary, ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  excerpt?: string;
  featured?: boolean;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  lead?: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Session {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  kicker?: string;
  price?: string;
  price_thb?: string;
  description?: string;
  button_label?: string;
  highlight?: boolean;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface HomePage {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  eyebrow?: string;
  headline?: string;
  lead?: string;
  primary_button?: string;
  secondary_link?: string;
  points?: { "title": string; "text"?: string | null }[];
  posts_eyebrow?: string;
  posts_title?: string;
  astro_eyebrow?: string;
  astro_title?: string;
  astro_text?: string;
  astro_button?: string;
  astro_note?: string;
  consult_eyebrow?: string;
  consult_title?: string;
  consult_text?: string;
  thai_link?: string;
  about_eyebrow?: string;
  about_title?: string;
  about_lead?: string;
  about_body?: string;
  about_link?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface ConsultPage {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  eyebrow?: string;
  headline?: string;
  lead?: string;
  thai_note?: string;
  thai_link?: string;
  steps_title?: string;
  steps?: { "title": string; "text"?: string | null }[];
  get_title?: string;
  get_list?: { "text": string }[];
  not_title?: string;
  not_list?: { "text": string }[];
  book_title?: string;
  book_text?: string;
  whatsapp_label?: string;
  whatsapp_number?: string;
  whatsapp_url?: string;
  whatsapp_button?: string;
  line_label?: string;
  line_id?: string;
  line_url?: string;
  line_button?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    posts: Post;
    pages: Page;
    sessions: Session;
    home_page: HomePage;
    consult_page: ConsultPage;
  }
}